// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "f450815b-6e5b-4e1f-b0ec-1ca849369ebd";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onMESSAGEChange();
void onAIRQUALITYChange();
void onHUMIDITYChange();
void onTEMPERATUREChange();

String mESSAGE;
CloudPercentage aIRQUALITY;
CloudPercentage hUMIDITY;
CloudTemperature tEMPERATURE;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(mESSAGE, READWRITE, ON_CHANGE, onMESSAGEChange);
  ArduinoCloud.addProperty(aIRQUALITY, READWRITE, ON_CHANGE, onAIRQUALITYChange);
  ArduinoCloud.addProperty(hUMIDITY, READWRITE, ON_CHANGE, onHUMIDITYChange);
  ArduinoCloud.addProperty(tEMPERATURE, READWRITE, ON_CHANGE, onTEMPERATUREChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
